name: Build

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        default: public-artifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build to public folder
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: public/
