name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Display gatsby-config before configure
        run: cat gatsby-config.ts
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          static_site_generator: gatsby
      - name: Display gatsby-config after configure
        run: cat gatsby-config.ts
      - name: Build to public folder
        env:
          PREFIX_PATHS: "true"
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: public/
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/
