name: Build

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        default: public-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          static_site_generator: gatsby
      - name: Build to public folder
        run: npm run build --prefix-paths
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: public/
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/
