name: Run Tests

on:
  push:
  workflow_call:
    inputs:
      stuff:
        description: "Testing stuff"
        required: false
        default: "v1"
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.stuff }}
      - run: echo "Finished 1"

  event-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo name ${{ github.event_name }}
