name: Run Tests
run-name: Running Matrix flow on ${{ github.ref }} or ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      stuff:
        description: "Testing stuff"
        required: false
        default: "v1"
        type: string
      ref-prefix:
        description: "Ref prefix"
        required: false
        default: "v1"
        type: string
      ref:
        description: "Ref"
        required: false
        default: "v1"
        type: string

jobs:
  tests:
    if: |
      inputs.ref-prefix && startsWith(github.ref, inputs.ref-prefix) ||
      github.ref == inputs.ref
    runs-on: ubuntu-latest
    steps:
      - run: echo stuff:${{ inputs.stuff }}
      - run: echo prefix:${{ inputs.ref-prefix }}
      - run: echo ref:${{ inputs.ref }}
      - run: echo github.ref_name:${{ github.ref_name }}
      - run: echo "Finished 1"
