name: Run Demo Call

on:
  workflow_call:
    inputs:
      stuff:
        description: "Testing stuff"
        required: false
        default: "v2-fork-subdir-2"
        type: string
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.stuff }}
      - run: echo "Finished 1"

  second:
    environment: test
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - run: echo second job

  third:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo never runs

  fourth:
    environment: test
    needs:
      - second
    runs-on: ubuntu-latest
    steps:
      - run: echo fourth job
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-vars
