name: Run Tests

on:
  push:

jobs:
  test-matrix:
    strategy:
      matrix:
        include:
          - ref: refs/heads/main
            env: in-main
          - ref-prefix: refs/heads/test-
            env: test
    uses: ./.github/workflows/demo_call.yml
    with:
      stuff: ${{ matrix.env }}
      ref-prefix: ${{ matrix.ref-prefix }}
      ref: ${{ matrix.ref }}