name: Run Demo Call

on:
  workflow_call:
    inputs:
      stuff:
        description: "Testing stuff"
        required: false
        default: "v2-fork-subdir-2"
        type: string
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.stuff }}
      - run: echo "Finished 1"

  second:
    environment: test
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - run: echo second job

      - name: echo secret
        env:
          supersecret: ${{ secrets.SECRET_1 }}
        run: echo $supersecret

  third:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo never runs

  fourth:
    name: Fourth Job
    environment: test
    needs:
      - second
    runs-on: ubuntu-latest
    steps:
      - run: echo fourth job
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-vars
        with:
          var1: ${{ vars.VAR_1 }}
          secret1: ${{ secrets.SECRET_1 }}
