name: Test, Build and Deploy dev

on:
  push:
    branches:
      - "release/gh-pages"
      # TODO: REMOVE BEFORE MERGING
      - "3-setup-workflows"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: tests
    uses: ./.github/workflows/build.yml
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
