name: Build and Deploy
on:
  workflow_run:
    workflows:
      - "Run Tests"
    branches:
      - "main"
      - "3-setup-workflows"
    types:
      - "completed"

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo stuff
        run: echo building
