name: Build and Deploy
on:
  push:
    branches:
      - "main"
      - "3-setup-workflows"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: echo stuff
        run: echo building
