on:
  pull_request:
  workflow_call:
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 48 2 * * *
name: Semgrep
jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: semgrep.sarif
      #     # Optional category for the results
      #     # Used to differentiate multiple results for one commit
      #     category: semgrep
      #   continue-on-error: true
      #   if: always()
