name: Run Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: "Testing version"
        required: false
        default: "v2"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running actions ${{ inputs.version }}
        uses: ./.github/actions/setup
      - name: Run Tests
        run: npm test
      - run: echo "Finished"
