name: Run Tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Tests
        run: npm test
