name: Run Tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  early:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo test

  tests:
    if: ${{ vars.RUN_TESTS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: stop job early
        if: ${{ vars.RUN_TESTS == 'false' }}
        run: exit 0
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Packages
        run: npm ci --legacy-peer-deps
      - name: Run Tests
        run: npm test
