name: Run Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    # TODO: REMOVE BEFORE MERGING
    # branches-ignore:
    #   - "3-setup-workflows"
  workflow_call:

jobs:
  early:
    if: ${{ vars.RUN_TESTS != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "${{ vars.RUN_TESTS }}"

  tests:
    if: ${{ vars.RUN_TESTS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup.yml
      - name: Run Tests
        run: npm test
