name: Run Tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_call:

jobs:
  early:
    if: ${{ vars.RUN_TESTS != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "${{ vars.RUN_TESTS }}"

  tests:
    if: ${{ vars.RUN_TESTS == 'true'  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Tests
        run: npm test
