name: Run Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Tests
        run: npm test
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --config=auto --sarif > semgrep.sarif
        # env:
        #   # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
        #   SEMGREP_RULES: "p/default p/react" # more at semgrep.dev/explore
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: semgrep
